language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t valegio/complex_dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true valegio/complex_dev npm run test -- --coverage

after_success:
  - docker build -t valegio/multi-client ./client
  - docker build -t valegio/multi-nginx ./nginx
  - docker build -t valegio/multi-server ./server
  - docker build -t valegio/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to DockerHub
  - docker push valegio/multi-client
  - docker push valegio/multi-nginx
  - docker push valegio/multi-server
  - docker push valegio/multi-worker
